services:
  - type: web
    name: backend-tienda
    env: python
    plan: free
    buildCommand: pip install -r backend_tienda/requirements.txt
    startCommand: cd backend_tienda && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /docs

