services:
  - type: web
    name: backend-tienda
    env: python
    plan: free
    rootDir: backend_tienda
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /docs

